server:
  workers: 2
  node:
    environment: production
    dataDir: /data/presto
    pluginDir: /usr/lib/presto/plugin
  log:
    presto:
      level: INFO
  config:
    path: /usr/lib/presto/etc
    pathCatalog: /usr/lib/presto/etc/catalog
    http:
      port: 8080
    authentication:
      type: PASSWORD
    https:
      port: 8443
      keystore:
        path: /usr/lib/presto/etc/keystore/keystore.jks
        mountpath: /usr/lib/presto/etc/keystore
        key: fwk_admin
    query:
      maxMemory: "4GB"
      maxMemoryPerNode: "1GB"
  jvm:
    maxHeapSize: "8G"
    gcMethod:
      type: "UseG1GC"
      g1:
        heapRegionSize: "32M"
  passwordauthenticator:
    name: file
    passwordfile: /usr/lib/presto/etc/auth/password.db
    mountpath: /usr/lib/presto/etc/auth

image:
  repository: docker-v2-repository-virtual-external.digital.oocl.com/prestosql/presto
  tag: 329
  pullPolicy: IfNotPresent
  securityContext:
    runAsUser: 1000
    runAsGroup: 1000

service:
  type: ClusterIP

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

hive:
  metastore:
    uri: thrift://metastore:9083
  s3:
    endpoint: 127.0.0.1
    ssl:
      enabled: false
    max-connections: 100
    aws-access-key: 
    aws-secret-key: 